[package]
name = 'narcissistic'
version = '0.1.0'
authors = ['Yaoxunyu <windc96@gmail.com>']
edition = '2018'

[dependencies]
itertools = '0.8'
lazyonce = '1.0'

# [dependencies.linked-list]
# git = 'https://github.com/contain-rs/linked-list'
